version: "3.8"

services:
  geoserver:
    build: .
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - ./data:/opt/geoserver/data_dir
